### ISSUE TITLE
Other: Filling Request for full OWL graph data

### ISSUE THREAD

**Issue by callahantiff** [UCDenver-ccp/kgEmbeddingEnrichment#3]
@zmaas - you stated that you might need the full OWL version of the graph used to generate the OWL-NETS property graph data I originally provided you. You can access that data for the next 5 days using the link provided below. Please let me know if you have any trouble downloading the data. 

*NOTE:* The file sizes for each of the linked data are large and may take a while to download.

**OWL Graph:**  
- [`PheKnowLator_Instance_RelationsOnly_NotClosed_OWL_KG.owl`](https://www.dropbox.com/s/9z02ooyudzzy6li/PheKnowLator_Instance_RelationsOnly_NotClosed_OWL_KG.owl?dl=1)  - `3.29 GB`
- [`PheKnowLator_Instance_RelationsOnly_NotClosed_OWL_Triples_Identifiers.txt`](https://www.dropbox.com/s/8jsopwgbpdaux70/PheKnowLator_Instance_RelationsOnly_NotClosed_OWL_Triples_Identifiers.txt?dl=1) - `4.96 GB`  

<br>

Please feel free to close this issue once you have downloaded the data.

**Comment by zmaas** [comment]
Thanks for uploading this! I have it downloaded now.

**Comment by callahantiff** [comment]
No problem! We can discuss it further when we meet tomorrow, I just wanted to make sure you had what you needed in the meantime!
